### PR TITLE
Fix Paraskevidekatriaphobia

### PR DESCRIPTION
**Pull request by hvox**
Add missing `bindAttribLocation` into shader initialization

### CODE REVIEW

**Comment by alcore** [comment]
Great, thanks for isolating it!

**Comment by hvox** [comment]
And thank you too!

**Comment by alcore** [comment]
... although: 

```
gl.bindAttribLocation(shaderProgram, 1, "vertex_normal");
gl.bindAttribLocation(shaderProgram, 1, "uv");
```
You're binding twice to the same index, if I understand it correctly. Is that intended?

**Comment by hvox** [comment]
According to [WebGL/GLES2 specification](https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glBindAttribLocation.xml), it is okay to bind multiple variables to the same index, and it is okay to bind indexes to non-existent variables(they will just be ignored during linking). So I just reuse the same index for different variables in different shaders.
_I felt smart when I came up with this code in my head. I felt less smart when I discovered that I forgot to write the code._

**Comment by alcore** [comment]
Alright - just wanted to double check. Sometimes typos etc. creep in when people are asked to change/adjust their code on the spot.

**Comment by hvox** [comment]
Thank you for caring!
And thank you for merging!

**Pull request merged**
