### PR TITLE
Update script.js

### PR DESCRIPTION
**Pull request by lynchbyte**
path for pngs updated

### CODE REVIEW

**Comment by alcore** [comment]
I just realized you didn't include an updated .zip (`games/triskatopia/.src/g.zip`) including this fix - and I accepted somewhat prematurely. Could you create another PR, with just the .zip, when you have a moment?

**Comment by lynchbyte** [comment]
Hi,

I have added the zip file here;
https://github.com/lynchbyte/js13k_Triskatopia/blob/main/archive.zip

I hope that's ok.  I really didn't want to fork the whole games repository.  I'm not very good on git and the thought of that made me very very nervous.

Cheers,

Shauna

**Comment by alcore** [comment]
Alright, thanks. I updated it for you.

That said - there's nothing to really be nervous about with Git. You couldn't possibly break anything accidentally, so it's just a learning experience. At worst, or at best - depending on perspective.

**Comment by lynchbyte** [comment]
Hi,

Me again,  I think it is a problem was gulp.  It was encoding the pngs. Doh!
***@***.***

I edited script.js on git,  PR should be there for your approval.


Could you please update the 2 png's files in /media.
https://github.com/lynchbyte/js13k_Triskatopia/blob/main/media/1.png
https://github.com/lynchbyte/js13k_Triskatopia/blob/main/media/blurPic.png

Here's the new zip;
https://github.com/lynchbyte/js13k_Triskatopia/blob/main/archive.zip

Sorry for being a pain.  Hopefully this is the fix.

Thanks.

**Comment by alcore** [comment]
Done and updated.

But next year, _please_, preview and test your game while it is still a draft, on the site, before you submit - at that stage you can edit it freely without anyone else involved, which is quite a lot simpler for everyone.

**Comment by alcore** [comment]
Sidenote: While your updated images displayed fine on my system, https://github.com/js13kGames/games/commit/84e9b2c4719826028c462d0448c48bffa93500ab has trouble displaying them, which signals to me there is probably something still wrong with how you're bundling/building them.

**Comment by lynchbyte** [comment]
Thank you. And will do for next year.

**Comment by lynchbyte** [comment]
Yes, agreed, I think there is something not quite right with gulp.  I never had to use {encoding: false}  before this year.
Looks like I will have to learn something new for next year. 😔

Thanks again for all your help.

function copyMedia() {

  return gulp.src('./src/media/*.*', {encoding: false} )
  .pipe(gulp.dest('dist/media'))

}

**Comment by alcore** [comment]
https://github.com/gulpjs/gulp/issues/2803 seems strictly related. There are some workarounds and fixes mentioned in that thread that you could try (if you haven't seen/tried them already, that is).

**Pull request merged**
