### PR TITLE
Update Paraskevidekatriaphobia

### PR DESCRIPTION
**Pull request by hvox**
Fix billions of rendering bugs, add shadows and some small improvements in physics.

### CODE REVIEW

**Comment by alcore** [comment]
o/

We've got an open discussion on https://slack.js13kgames.com regarding the fairness of accepting fixes past the deadline. As it is, it's ambigous and arbitrary, and ultimately up to me and Ender to decide.

In the vein of a prior case like https://github.com/js13kGames/games/pull/4, if you can isolate the rendering issue into a separate PR, then I'd be willing to accept it. IIRC the issue was missing `bindAttribLocation`, ergo possibly uninitialized memory, ergo platform specific undefined behavior, which is fine for me to make a rule exception for.

The other stuff we could _maybe_ accept after voting has concluded.

**Comment by hvox** [comment]
Fair

**Comment by KilledByAPixel** [comment]
@hvox don't worry, your fix WILL be accepted after the voting deadline no matter what. I will move mountains to make sure it happens.

**Comment by end3r** [comment]
This is a delicate topic given how we made a mega thread on Slack out of it, but I'm sure we'll settle with the best possible option. For now let's merge the isolated critical fix and keep the other improvements separately, so they could be merged as well if the community don't mind. We did discuss multiple options on Slack though like internal vs external post-compo versions, so the fixed build will land somewhere, eventually, we just need a bit more time to make sure we agree on the details.

**Comment by alcore** [comment]
The key here being `if the **community** don't mind` - not `no matter what` willed into being by a single person. Sorry you got subjected to that, @hvox.

That said and until we have a community decision - what we do have as a new feature is that you can self-host your game in whichever way you prefer, free of any of the competition's limits, and just link to it as a Director's Cut on https://js13kgames.com/2024/games/paraskevidekatriaphobia. It will show up as an additional "Play" button next to the competition version once voting has concluded (automatically).

**Comment by KilledByAPixel** [comment]
@alcore hvox should not be subject to rules or decisions made afterwards! it clearly says on the website "we may let minor exceptions slide if warranted by the benefit of the competition overall." To me that means "we" in this case the organizers of the competition may let post deadline fixes slide. not a decision by the community but in fact willed into existence by you and ender. you can offload that responsibility to the community if you desire but i wouldn't recommend it. 

maybe i misread that part of the rules but i did read it many times and was pretty clear on it's meaning as i have summited fixes after the deadline and many others have also. in fact as i mentioned, i would not consider participating if fixes were impossible, and i really want to participate. 

it is we discussed earlier but that's your fault for poorly wording the rules if that was not your intent. if your goal was to state that fixes before the deadline may be accepted (i think thats what you said, please correct me if wrong), that makes no sense because fixes before the deadline are always accepted. that is why you worked so hard on the draft system. so it can only be interpreted to mean that fixes after the deadline are in some cases allowed.

@hvox has updates ready within a week after the deadline and should be commended. i'd like to take a moment to thank them personally for going above and beyond. the rules state that post compo fixes may be let slide for benefit of the compaction overall. i will argue to my death that if will be better for the competition if at least after voting concludes you click the button to accept the pull request.

**Comment by KilledByAPixel** [comment]
@alcore  While we are on the subject of one person trying to control things. I meant to ask you, who has control of the source code for the js13k website? Is that something one person should have control over, or is that something the community should be able to participate in? Isn't JS13K all about open source? All games are required to post their code on github. I posted my code every time. Where is the code for the website?

From what I understand, not even Ender has access to the source code. If so, this is a very dangerous situation because should anything happen to you, we are all in trouble because we don't have the source code. This is what we called the "getting hit by a bus test" at work. if one person gets hit by a bus it should not ruin the whole project. really the js13k website code should be open source so we can all benefit from it.

Normally I'd write this all in a DM but you seem to want to post screenshots of those.

**Comment by alcore** [comment]
> To me that means "we"

To _you_, personally.

vs

> if warranted by the benefit of the competition overall.

You don't seem to view the community and its interests as benefitting the competition overall, and that's your first problem.

> it is we discussed earlier but that's your fault for poorly wording the rules if that was not your intent.
The rule was worded as follows:

**Back in 2012**:
> No submissions will be accepted after the end of the competition.

**Since... 2019, and no sooner:**
> No submissions will be accepted after the end of the competition, although there may be exceptions to that.

**And since 2024:**
> Past this date, no further submissions will be accepted (we may let minor exceptions slide if warranted by the benefit of the competition overall).

That was after several discussions with Ender over the last 2 years. The meaning has not changed at all. It was reworded to clarify that Sept 13th is the deadline ("this date") instead of "end of the competition" which is not defined, and that the intent of those exceptions has always been to allow "minor" exceptions, which we understood - and still understand - as _fixes_ that are _minor_ in scope.

As such:

> hvox should not be subject to rules or decisions made afterwards

By definition, if it is up to me and Ender to decide, as you yourself stated, then what exactly is your point? You, yourself stated, we can decide and rule as we see fit, and if we see fit to let the community decide, then that's that.

Your arguments keep being illogical and are continously discordant. To me this looks like you are arguing for the sake of arguing, in bad faith, in order to "win" an argument that no one is really having with you.

> it is we discussed earlier but that's your fault for poorly wording the rules if that was not your intent. if your goal was to state that fixes before the deadline may be accepted (i think thats what you said, please correct me if wrong),

No, I did not. You are, **once again**, putting words in other people's mouths and intentions in their heads. This time, supposedly, "misunderstanding" it. You understood it perfectly well on Slack. What changed?

Additionally, as other people have already told you numerous times - you continue just blatantly and entirely disregarding the concept of other people, other views, other values. Your understanding or not understanding something in one particular way does in no way automatically mean something is "poorly worded" - it only means you understand it differently than others, which by itself does not make it correct or wrong either. You continue to mistake your personal beliefs and values for an objective truth, and continue projecting that onto others.

> but i wouldn't recommend it.

Your recommendations have been heard in the thread dedicated to those voices - and the majority of the voices did not agree with you. That's all there is to in _this_ respect.

> not a decision by the community but in fact willed into existence by you and ender.

As you can read, again, but somehow keep, again, disregarding entirely in both Ender's statement _and_ mine - it is a done deal. We both agree on the matter, and our view happens to be in sync with what the majority voiced. And that's all there is to it in _this_ respect at the moment. The details are up in the air.

While it is unfortunate that not everyone can be pleased with everything, it is the opposite of willing it into existence single-handedly and "no matter what", like you claimed _you_ would.



> @alcore While we are on the subject of (...)

Yes, you are objectively wrong, once again.
That said, you are, of course, free to write your own if you feel anything is amiss or that you can do anything better, for the betterment of the community that you claim to care _so_ much about (unless, of course, that community decides anything that isn't to your personal preference - then, apparently, you don't "recommend" it).

What I got to read again, however, is that apparently you do not only feel entitled to other people's time - you also feel entitled to their work. And thanks for your consideration regarding my well being. Clearly your entitlement to the fruits of my labor goes even beyond my death.

You do realize that I've been here since 2012 and the competition had been running on my volunteer work long before you ever heard of it, right? And that I have never published that work with an open source license (vide https://github.com/js13kGames/js13kgames.com-legacy/tree/php) nor explicitly licensed it to anyone, and yet somehow that wasn't ever a problem until you deemed your egotrip warranted making it one. Well, you made it one - congratulations.

**While you are free to write your own, what you are not free to do, however, is hijacking another person's good faith thread and derailing it for your own personal agenda. Again. Your behavior is turning into straight up abusive harassment, actively seeking out ways to inflame and incite conflicts in places that did not invite you to do so. This ends here and now.**

**Comment by end3r** [comment]
As I said, we'll iron out the details of the "fixes being accepted past the deadline" gray area and I'm sure this will clear the situation. I appreciate all your efforts to make this compo the best it could be, thank you.

The critical fix of `bindAttribLocation` was already [merged](https://github.com/js13kGames/games/pull/21), and we'll get back to the other fixes when the consensus is met.

**Pull request closed without merging**
